import Testing
import Foundation
@testable import ThemeKitGenerator

@Suite("ThemeFileGenerator")
struct ThemeFileGeneratorTests {

    let fullJSON = Data("""
    {
        "styles": {
            "colors": ["surface", {"name": "primary", "style": "primaryColor"}],
            "gradients": ["primary"]
        }
    }
    """.utf8)

    let colorsOnlyJSON = Data("""
    {
        "styles": {
            "colors": ["surface"]
        }
    }
    """.utf8)

    // MARK: - File list

    @Test func fullConfig_generatesAllExpectedFiles() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files
        let names = Set(files.map(\.name))

        #expect(names.contains("ThemeShapeStyle.swift"))
        #expect(names.contains("Environment+Theme.swift"))
        #expect(names.contains("Theme.swift"))
        #expect(names.contains("ThemeColors.swift"))
        #expect(names.contains("ThemeGradients.swift"))
        #expect(names.contains("Theme+CopyWith.swift"))
        #expect(names.contains("ThemeColors+CopyWith.swift"))
        #expect(names.contains("ThemeGradients+CopyWith.swift"))
        #expect(names.contains("ShapeStyle+ThemeColors.swift"))
        #expect(names.contains("ShapeStyle+ThemeGradients.swift"))
        #expect(names.contains("Theme+Defaults.swift"))
        #expect(files.count == 11)
    }

    @Test func colorsOnly_generatesSubset() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: colorsOnlyJSON).files
        let names = Set(files.map(\.name))

        // Static files always present
        #expect(names.contains("ThemeShapeStyle.swift"))
        #expect(names.contains("Environment+Theme.swift"))
        #expect(names.contains("Theme.swift"))
        #expect(names.contains("Theme+CopyWith.swift"))

        // Colors category files
        #expect(names.contains("ThemeColors.swift"))
        #expect(names.contains("ThemeColors+CopyWith.swift"))
        #expect(names.contains("ShapeStyle+ThemeColors.swift"))

        // Defaults scaffold
        #expect(names.contains("Theme+Defaults.swift"))

        // Gradients/Shadows should NOT be present
        #expect(!names.contains("ThemeGradients.swift"))
        #expect(!names.contains("ThemeShadows.swift"))

        #expect(files.count == 8)
    }

    // MARK: - Generated header

    @Test func allFiles_startWithGeneratedHeader() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files
        for file in files where file.name != "Theme+Defaults.swift" {
            #expect(file.content.hasPrefix("// Generated by ThemeKit — do not edit"),
                    "File \(file.name) missing generated header")
        }
    }

    @Test func defaultsFile_hasNoGeneratedHeader() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files
        let defaults = try #require(files.first { $0.name == "Theme+Defaults.swift" })
        #expect(!defaults.content.hasPrefix("// Generated by ThemeKit"))
    }

    // MARK: - Content patterns

    @Test func themeStruct_containsCategoryProperties() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files
        let themeFile = try #require(files.first { $0.name == "Theme.swift" })

        #expect(themeFile.content.contains("let colors: ThemeColors"))
        #expect(themeFile.content.contains("let gradients: ThemeGradients"))
        #expect(themeFile.content.contains("struct Theme"))
    }

    @Test func categoryStruct_containsTokenProperties() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files
        let colorsFile = try #require(files.first { $0.name == "ThemeColors.swift" })

        #expect(colorsFile.content.contains("let surface: ThemeAdaptiveStyle<Color>"))
        #expect(colorsFile.content.contains("let primary: ThemeAdaptiveStyle<Color>"))
        #expect(colorsFile.content.contains("struct ThemeColors"))
    }

    @Test func shapeStyleExtension_usesCorrectStyleNames() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files
        let colorsExt = try #require(files.first { $0.name == "ShapeStyle+ThemeColors.swift" })

        // "surface" token: name == style, so ShapeStyle property is "surface"
        #expect(colorsExt.content.contains("static var surface: Self"))
        #expect(colorsExt.content.contains("\\.colors.surface"))

        // "primary" token with style "primaryColor"
        #expect(colorsExt.content.contains("static var primaryColor: Self"))
        #expect(colorsExt.content.contains("\\.colors.primary"))
    }

    @Test func shapeStyleExtension_constrainsToCorrectType() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files

        let colorsExt = try #require(files.first { $0.name == "ShapeStyle+ThemeColors.swift" })
        #expect(colorsExt.content.contains("ThemeShapeStyle<Color>"))

        let gradientsExt = try #require(files.first { $0.name == "ShapeStyle+ThemeGradients.swift" })
        #expect(gradientsExt.content.contains("ThemeShapeStyle<Gradient>"))
    }

    @Test func copyWith_themeUsesOptionalParams() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files
        let copyWith = try #require(files.first { $0.name == "Theme+CopyWith.swift" })

        #expect(copyWith.content.contains("colors: ThemeColors? = nil"))
        #expect(copyWith.content.contains("gradients: ThemeGradients? = nil"))
        #expect(copyWith.content.contains("colors: colors ?? self.colors"))
    }

    @Test func copyWith_categoryUsesOptionalParams() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files
        let copyWith = try #require(files.first { $0.name == "ThemeColors+CopyWith.swift" })

        #expect(copyWith.content.contains("surface: ThemeAdaptiveStyle<Color>? = nil"))
        #expect(copyWith.content.contains("surface: surface ?? self.surface"))
    }

    @Test func themeShapeStyle_containsResolveMethod() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files
        let shapeStyle = try #require(files.first { $0.name == "ThemeShapeStyle.swift" })

        #expect(shapeStyle.content.contains("func resolve(in environment: EnvironmentValues)"))
        #expect(shapeStyle.content.contains("environment.theme[keyPath: keyPath]"))
        #expect(shapeStyle.content.contains("environment.colorScheme"))
    }

    @Test func environmentExtension_containsThemeEntry() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files
        let envFile = try #require(files.first { $0.name == "Environment+Theme.swift" })

        #expect(envFile.content.contains("@Entry"))
        #expect(envFile.content.contains("var theme: Theme"))
    }

    // MARK: - Defaults scaffold

    @Test func defaults_containsThemeExtensionWithCategories() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files
        let defaults = try #require(files.first { $0.name == "Theme+Defaults.swift" })

        #expect(defaults.content.contains("extension Theme"))
        #expect(defaults.content.contains("colors: .`default`"))
        #expect(defaults.content.contains("gradients: .`default`"))
    }

    @Test func defaults_containsCategoryDefaults() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files
        let defaults = try #require(files.first { $0.name == "Theme+Defaults.swift" })

        #expect(defaults.content.contains("extension ThemeColors"))
        #expect(defaults.content.contains("extension ThemeGradients"))
        #expect(defaults.content.contains("surface:"))
        #expect(defaults.content.contains("primary:"))
    }

    @Test func defaults_colorsUsePlaceholders() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files
        let defaults = try #require(files.first { $0.name == "Theme+Defaults.swift" })

        #expect(defaults.content.contains(".init(light: <#light#>, dark: <#dark#>)"))
    }

    @Test func defaults_gradientsUseMultilineFormat() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files
        let defaults = try #require(files.first { $0.name == "Theme+Defaults.swift" })

        #expect(defaults.content.contains("light: .init(colors: [<#color#>, <#color#>])"))
        #expect(defaults.content.contains("dark:  .init(colors: [<#color#>, <#color#>])"))
    }

    @Test func defaults_importsThemeKit() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files
        let defaults = try #require(files.first { $0.name == "Theme+Defaults.swift" })

        #expect(defaults.content.contains("import SwiftUI"))
        #expect(defaults.content.contains("import ThemeKit"))
    }

    // MARK: - ThemeShapeStyle conformances

    @Test func themeShapeStyle_conformsToEquatable() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files
        let shapeStyle = try #require(files.first { $0.name == "ThemeShapeStyle.swift" })

        #expect(shapeStyle.content.contains("Equatable"))
    }

    @Test func themeShapeStyle_constrainsGenericToSendableAndCodable() throws {
        let files = try ThemeFileGenerator().generate(fromJSON: fullJSON).files
        let shapeStyle = try #require(files.first { $0.name == "ThemeShapeStyle.swift" })

        #expect(shapeStyle.content.contains("Style: ShapeStyle & Sendable & Codable"))
    }

    // MARK: - Config Section

    @Test func configSection_providesOutputPath() throws {
        let jsonWithConfig = Data("""
        {
            "styles": {
                "colors": ["surface"]
            },
            "config": {
                "outputPath": "UI/Theme"
            }
        }
        """.utf8)

        let result = try ThemeFileGenerator().generate(fromJSON: jsonWithConfig)
        #expect(result.outputPath == "UI/Theme")
        #expect(!result.files.isEmpty)
    }

    @Test func missingConfig_usesDefaultOutputPath() throws {
        let result = try ThemeFileGenerator().generate(fromJSON: colorsOnlyJSON)
        #expect(result.outputPath == ".")
    }
}
