import Testing
import Foundation
@testable import ThemeKitGenerator

@Suite("ThemePreviewGenerator")
struct ThemePreviewGeneratorTests {

    let colorsOnlyConfig = ThemeConfig(
        colors: [
            ThemeToken(name: "surface", style: "surface"),
            ThemeToken(name: "primary", style: "primaryColor")
        ]
    )

    let fullConfig = ThemeConfig(
        colors: [ThemeToken(name: "surface", style: "surface")],
        gradients: [ThemeToken(name: "primary", style: "primary")],
        meshGradients: [ThemeToken(name: "aurora", style: "aurora")],
        shadows: [ThemeToken(name: "card", style: "cardShadow")]
    )

    // MARK: - File generation

    @Test func generate_returnsCorrectFileName() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.name == "Theme+Preview.swift")
    }

    @Test func generate_includesGeneratedHeader() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.hasPrefix("// Generated by ThemeKit — do not edit"))
    }

    @Test func generate_importsSwiftUIAndThemeKit() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("import SwiftUI"))
        #expect(file.content.contains("import ThemeKit"))
    }

    @Test func generate_containsThemePreviewStruct() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("public struct ThemePreview: View"))
        #expect(file.content.contains("public var body: some View"))
    }

    @Test func generate_doesNotContainEnvironmentProperties() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(!file.content.contains("@Environment"))
    }

    @Test func generate_containsPreviewMacro() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("#Preview"))
        #expect(file.content.contains("ThemePreview()"))
    }

    // MARK: - Colors section

    @Test func colorsPresent_includesColorsSection() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("// MARK: - Colors"))
        #expect(file.content.contains("Text(\"Colors\")"))
        #expect(file.content.contains("ColorSwatch"))
    }

    @Test func colorsPresent_includesAllColorTokens() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("ColorSwatch(name: \"surface\", style: .surface)"))
        #expect(file.content.contains("ColorSwatch(name: \"primary\", style: .primaryColor)"))
    }

    @Test func colorsAbsent_excludesColorsSection() {
        let config = ThemeConfig(gradients: [ThemeToken(name: "primary", style: "primary")])
        let file = ThemePreviewGenerator().generate(from: config)
        #expect(!file.content.contains("// MARK: - Colors"))
        #expect(!file.content.contains("ColorSwatch"))
    }

    // MARK: - Gradients section

    @Test func gradientsPresent_includesGradientsSection() {
        let file = ThemePreviewGenerator().generate(from: fullConfig)
        #expect(file.content.contains("// MARK: - Gradients"))
        #expect(file.content.contains("Text(\"Gradients\")"))
        #expect(file.content.contains("GradientStrip"))
    }

    @Test func gradientsPresent_includesAllGradientTokens() {
        let file = ThemePreviewGenerator().generate(from: fullConfig)
        #expect(file.content.contains("GradientStrip(name: \"primary\", style: .primary)"))
    }

    @Test func gradientsAbsent_excludesGradientsSection() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(!file.content.contains("// MARK: - Gradients"))
        #expect(!file.content.contains("GradientStrip"))
    }

    // MARK: - Shadows section

    @Test func shadowsPresent_includesShadowsSection() {
        let file = ThemePreviewGenerator().generate(from: fullConfig)
        #expect(file.content.contains("// MARK: - Shadows"))
        #expect(file.content.contains("Text(\"Shadows\")"))
        #expect(file.content.contains("ShadowCard"))
    }

    @Test func shadowsPresent_includesAllShadowTokens() {
        let file = ThemePreviewGenerator().generate(from: fullConfig)
        #expect(file.content.contains("ShadowCard(name: \"card\", style: .background.cardShadow)"))
    }

    @Test func shadowsAbsent_excludesShadowsSection() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(!file.content.contains("// MARK: - Shadows"))
        #expect(!file.content.contains("ShadowCard"))
    }

    // MARK: - Mesh Gradients section

    @Test func meshGradientsPresent_includesMeshGradientsSection() {
        let file = ThemePreviewGenerator().generate(from: fullConfig)
        #expect(file.content.contains("// MARK: - Mesh Gradients"))
        #expect(file.content.contains("Text(\"Mesh Gradients\")"))
        #expect(file.content.contains("MeshGradientCard"))
    }

    @Test func meshGradientsPresent_includesAllMeshGradientTokens() {
        let file = ThemePreviewGenerator().generate(from: fullConfig)
        #expect(file.content.contains("MeshGradientCard(name: \"aurora\", style: .aurora)"))
    }

    @Test func meshGradientsAbsent_excludesMeshGradientsSection() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(!file.content.contains("// MARK: - Mesh Gradients"))
        #expect(!file.content.contains("MeshGradientCard"))
    }

    // MARK: - Preview components

    @Test func generate_includesColorSwatchComponent() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("private struct ColorSwatch<Style: ShapeStyle>: View"))
    }

    @Test func generate_includesGradientStripComponent() {
        let config = ThemeConfig(gradients: [ThemeToken(name: "primary", style: "primary")])
        let file = ThemePreviewGenerator().generate(from: config)
        #expect(file.content.contains("private struct GradientStrip<Style: ShapeStyle>: View"))
    }

    @Test func generate_includesShadowCardComponent() {
        let config = ThemeConfig(shadows: [ThemeToken(name: "card", style: "card")])
        let file = ThemePreviewGenerator().generate(from: config)
        #expect(file.content.contains("private struct ShadowCard<Style: ShapeStyle>: View"))
    }

    @Test func generate_includesMeshGradientCardComponent() {
        let config = ThemeConfig(meshGradients: [ThemeToken(name: "aurora", style: "aurora")])
        let file = ThemePreviewGenerator().generate(from: config)
        #expect(file.content.contains("private struct MeshGradientCard<Style: ShapeStyle>: View"))
    }

    // MARK: - Layout structure

    @Test func generate_usesScrollView() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("ScrollView"))
    }

    @Test func generate_usesVStackForSections() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("VStack(alignment: .leading, spacing:"))
    }

    @Test func emptyConfig_generatesValidPreviewWithNoSections() {
        let config = ThemeConfig()
        let file = ThemePreviewGenerator().generate(from: config)

        #expect(file.name == "Theme+Preview.swift")
        #expect(file.content.contains("public struct ThemePreview: View"))
        #expect(file.content.contains("ScrollView"))
        #expect(!file.content.contains("// MARK: - Colors"))
        #expect(!file.content.contains("// MARK: - Gradients"))
        #expect(!file.content.contains("// MARK: - Mesh Gradients"))
        #expect(!file.content.contains("// MARK: - Shadows"))
    }
}
