import Testing
import Foundation
@testable import ThemeKitGenerator

@Suite("ThemePreviewGenerator")
struct ThemePreviewGeneratorTests {

    let colorsOnlyConfig = ThemeConfig(
        colors: [
            ThemeToken(name: "surface", style: "surface"),
            ThemeToken(name: "primary", style: "primaryColor")
        ]
    )

    let fullConfig = ThemeConfig(
        colors: [ThemeToken(name: "surface", style: "surface")],
        gradients: [ThemeToken(name: "primary", style: "primary")],
        shadows: [ThemeToken(name: "card", style: "cardShadow")]
    )

    // MARK: - File generation

    @Test func generate_returnsCorrectFileName() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.name == "Theme+Preview.swift")
    }

    @Test func generate_includesGeneratedHeader() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.hasPrefix("// Generated by ThemeKit — do not edit"))
    }

    @Test func generate_importsSwiftUIAndThemeKit() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("import SwiftUI"))
        #expect(file.content.contains("import ThemeKit"))
    }

    @Test func generate_containsThemePreviewStruct() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("public struct ThemePreview: View"))
        #expect(file.content.contains("public var body: some View"))
    }

    @Test func generate_containsEnvironmentTheme() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("@Environment(\\.theme) var theme"))
        #expect(file.content.contains("@Environment(\\.self) var environment"))
    }

    @Test func generate_containsPublicInit() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("public init() {}"))
    }

    @Test func generate_containsPreviewMacro() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("#Preview"))
        #expect(file.content.contains("ThemePreview()"))
    }

    // MARK: - Colors section

    @Test func colorsPresent_includesColorsSection() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("// MARK: - Colors"))
        #expect(file.content.contains("Text(\"Colors\")"))
        #expect(file.content.contains("ColorSwatch"))
    }

    @Test func colorsPresent_includesAllColorTokens() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("ColorSwatch(name: \"surface\", color: theme.colors.surface.resolved(in: environment))"))
        #expect(file.content.contains("ColorSwatch(name: \"primary\", color: theme.colors.primary.resolved(in: environment))"))
    }

    @Test func colorsAbsent_excludesColorsSection() {
        let config = ThemeConfig(gradients: [ThemeToken(name: "primary", style: "primary")])
        let file = ThemePreviewGenerator().generate(from: config)
        #expect(!file.content.contains("// MARK: - Colors"))
        #expect(!file.content.contains("ColorSwatch"))
    }

    // MARK: - Gradients section

    @Test func gradientsPresent_includesGradientsSection() {
        let file = ThemePreviewGenerator().generate(from: fullConfig)
        #expect(file.content.contains("// MARK: - Gradients"))
        #expect(file.content.contains("Text(\"Gradients\")"))
        #expect(file.content.contains("GradientStrip"))
    }

    @Test func gradientsPresent_includesAllGradientTokens() {
        let file = ThemePreviewGenerator().generate(from: fullConfig)
        #expect(file.content.contains("GradientStrip(name: \"primary\", gradient: theme.gradients.primary.resolved(in: environment))"))
    }

    @Test func gradientsAbsent_excludesGradientsSection() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(!file.content.contains("// MARK: - Gradients"))
        #expect(!file.content.contains("GradientStrip"))
    }

    // MARK: - Shadows section

    @Test func shadowsPresent_includesShadowsSection() {
        let file = ThemePreviewGenerator().generate(from: fullConfig)
        #expect(file.content.contains("// MARK: - Shadows"))
        #expect(file.content.contains("Text(\"Shadows\")"))
        #expect(file.content.contains("ShadowCard"))
    }

    @Test func shadowsPresent_includesAllShadowTokens() {
        let file = ThemePreviewGenerator().generate(from: fullConfig)
        #expect(file.content.contains("ShadowCard(name: \"card\", shadow: theme.shadows.card.resolved(in: environment))"))
    }

    @Test func shadowsAbsent_excludesShadowsSection() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(!file.content.contains("// MARK: - Shadows"))
        #expect(!file.content.contains("ShadowCard"))
    }

    // MARK: - Preview components

    @Test func generate_includesColorSwatchComponent() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("private struct ColorSwatch: View"))
    }

    @Test func generate_includesGradientStripComponent() {
        let config = ThemeConfig(gradients: [ThemeToken(name: "primary", style: "primary")])
        let file = ThemePreviewGenerator().generate(from: config)
        #expect(file.content.contains("private struct GradientStrip: View"))
    }

    @Test func generate_includesShadowCardComponent() {
        let config = ThemeConfig(shadows: [ThemeToken(name: "card", style: "card")])
        let file = ThemePreviewGenerator().generate(from: config)
        #expect(file.content.contains("private struct ShadowCard: View"))
    }

    // MARK: - Layout structure

    @Test func generate_usesScrollView() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("ScrollView"))
    }

    @Test func generate_usesVStackForSections() {
        let file = ThemePreviewGenerator().generate(from: colorsOnlyConfig)
        #expect(file.content.contains("VStack(alignment: .leading, spacing:"))
    }
}
