public struct CategoryStructGenerator: Sendable {

    public init() {}

    public func generate(category: ThemeCategory, tokens: [ThemeToken]) -> GeneratedFile {
        let properties = tokens.map { token in
            "    public let \(token.name): ThemeAdaptiveStyle<\(category.styleType)>"
        }.joined(separator: "\n")

        let initParams = tokens.map { token in
            "        \(token.name): ThemeAdaptiveStyle<\(category.styleType)>"
        }.joined(separator: ",\n")

        let initAssignments = tokens.map { token in
            "        self.\(token.name) = \(token.name)"
        }.joined(separator: "\n")

        let content = """
        // Generated by ThemeKit — do not edit

        import SwiftUI
        import ThemeKit

        public struct \(category.structName): Sendable, Codable, Equatable {
        \(properties)

            public init(
        \(initParams)
            ) {
        \(initAssignments)
            }
        }

        """
        return GeneratedFile(name: "\(category.structName).swift", content: content)
    }
}
