nonisolated public struct CopyWithGenerator: Sendable {

    nonisolated public init() {}

    nonisolated public func generateForTheme(config: ThemeConfig) -> GeneratedFile {
        let categories = config.categories

        let params = categories.map { category in
            "        \(category.propertyName): \(category.structName)? = nil"
        }.joined(separator: ",\n")

        let args = categories.map { category in
            "            \(category.propertyName): \(category.propertyName) ?? self.\(category.propertyName)"
        }.joined(separator: ",\n")

        let content = """
        // Generated by ThemeKit — do not edit

        import SwiftUI
        import ThemeKit

        extension Theme {
            nonisolated public func copyWith(
        \(params)
            ) -> Theme {
                Theme(
        \(args)
                )
            }
        }

        """
        return GeneratedFile(name: "Theme+CopyWith.swift", content: content)
    }

    nonisolated public func generateForCategory(category: ThemeCategory, tokens: [ThemeToken]) -> GeneratedFile {
        let params = tokens.map { token in
            "        \(token.name): ThemeAdaptiveStyle<\(category.styleType)>? = nil"
        }.joined(separator: ",\n")

        let args = tokens.map { token in
            "            \(token.name): \(token.name) ?? self.\(token.name)"
        }.joined(separator: ",\n")

        let content = """
        // Generated by ThemeKit — do not edit

        import SwiftUI
        import ThemeKit

        extension \(category.structName) {
            nonisolated public func copyWith(
        \(params)
            ) -> \(category.structName) {
                \(category.structName)(
        \(args)
                )
            }
        }

        """
        return GeneratedFile(name: "\(category.structName)+CopyWith.swift", content: content)
    }
}
