nonisolated public struct EnvironmentThemeGenerator: Sendable {

    nonisolated public init() {}

    nonisolated public func generate(androidSupport: Bool = false) -> GeneratedFile {
        let content = if androidSupport {
            """
            // Generated by ThemeKit — do not edit

            import SwiftUI

            nonisolated private struct ThemeEnvironmentKey: EnvironmentKey {
                static let defaultValue: Theme = .default
            }

            nonisolated extension EnvironmentValues {
                public var theme: Theme {
                    get { self[ThemeEnvironmentKey.self] }
                    set { self[ThemeEnvironmentKey.self] = newValue }
                }
            }

            """
        } else {
            """
            // Generated by ThemeKit — do not edit

            import SwiftUI

            nonisolated extension EnvironmentValues {
                @Entry public var theme: Theme = .default
            }

            """
        }
        return GeneratedFile(name: "Environment+Theme.swift", content: content)
    }
}
