public struct EnvironmentThemeGenerator: Sendable {

    public init() {}

    public func generate() -> GeneratedFile {
        let content = """
        // Generated by ThemeKit — do not edit

        import SwiftUI

        extension EnvironmentValues {
            @Entry public var theme: Theme = .default
        }

        """
        return GeneratedFile(name: "Environment+Theme.swift", content: content)
    }
}
