nonisolated public struct ShapeStyleExtensionGenerator: Sendable {

    nonisolated public init() {}

    nonisolated public func generate(category: ThemeCategory, tokens: [ThemeToken]) -> GeneratedFile {
        let staticProperties = tokens.map { token in
            "    public static var \(token.style): Self { .init(keyPath: \\.\(category.propertyName).\(token.name)) }"
        }.joined(separator: "\n")

        var content = """
        // Generated by ThemeKit — do not edit

        import SwiftUI
        import ThemeKit

        // ShapeStyle extensions are not available in SkipFuseUI on Android.
        #if !os(Android)
        nonisolated extension ShapeStyle where Self == ThemeShapeStyle<\(category.styleType)> {
        \(staticProperties)
        }

        """

        if category == .shadows {
            let instanceProperties = tokens.map { token in
                "    public var \(token.style): ThemeShadowedStyle<Self> { .init(base: self, shadowKeyPath: \\.\(category.propertyName).\(token.name)) }"
            }.joined(separator: "\n")

            content += """

            nonisolated extension ShapeStyle {
            \(instanceProperties)
            }

            """
        }

        content += "#endif\n"

        return GeneratedFile(name: "ShapeStyle+\(category.structName).swift", content: content)
    }
}
