public struct ShapeStyleExtensionGenerator: Sendable {

    public init() {}

    public func generate(category: ThemeCategory, tokens: [ThemeToken]) -> GeneratedFile {
        let properties = tokens.map { token in
            "    public static var \(token.style): Self { .init(keyPath: \\.\(category.propertyName).\(token.name)) }"
        }.joined(separator: "\n")

        let content = """
        // Generated by ThemeKit — do not edit

        import SwiftUI
        import ThemeKit

        extension ShapeStyle where Self == ThemeShapeStyle<\(category.styleType)> {
        \(properties)
        }

        """
        return GeneratedFile(name: "ShapeStyle+\(category.structName).swift", content: content)
    }
}
