nonisolated public struct ThemeShadowedStyleGenerator: Sendable {

    nonisolated public init() {}

    nonisolated public func generate() -> GeneratedFile {
        let content = """
        // Generated by ThemeKit — do not edit

        import SwiftUI
        import ThemeKit

        // `@unchecked Sendable` because the stored `shadowKeyPath` is a read-only
        // `KeyPath` over the `Sendable` `Theme` type. Sendability is asserted
        // here rather than through a blanket retroactive `KeyPath: Sendable`
        // conformance, which would leak into every consumer and conflict with
        // libraries (e.g. TCA) that manage key-path sendability themselves.
        nonisolated public struct ThemeShadowedStyle<Base: ShapeStyle>: ShapeStyle, @unchecked Sendable {
            let base: Base
            let shadowKeyPath: KeyPath<Theme, ThemeAdaptiveStyle<Shadow>>

            nonisolated public init(base: Base, shadowKeyPath: KeyPath<Theme, ThemeAdaptiveStyle<Shadow>>) {
                self.base = base
                self.shadowKeyPath = shadowKeyPath
            }

            nonisolated public func resolve(in environment: EnvironmentValues) -> some ShapeStyle {
                let shadow = environment.theme[keyPath: shadowKeyPath]
                    .resolved(in: environment)
                guard let shadowStyle = shadow.shadowStyle else {
                    return AnyShapeStyle(base)
                }
                return AnyShapeStyle(base.shadow(shadowStyle))
            }
        }

        extension ThemeShadowedStyle: Equatable where Base: Equatable {}

        """
        return GeneratedFile(name: "ThemeShadowedStyle.swift", content: content)
    }
}
