nonisolated public struct ThemePreviewGenerator: Sendable {

    nonisolated public init() {}

    nonisolated public func generate(from config: ThemeConfig) -> GeneratedFile {
        var sections: [String] = []
        var components: [String] = []

        // Generate color swatches if colors present
        if config.categories.contains(.colors) {
            let tokens = ThemeCategory.colors.tokens(from: config)
            sections.append(colorSwatchesSection(tokens: tokens))
            components.append(colorSwatchComponent())
        }

        // Generate gradient strips if gradients present
        if config.categories.contains(.gradients) {
            let tokens = ThemeCategory.gradients.tokens(from: config)
            sections.append(gradientStripsSection(tokens: tokens))
            components.append(gradientStripComponent())
        }

        // Generate shadow showcase if shadows present
        if config.categories.contains(.shadows) {
            let tokens = ThemeCategory.shadows.tokens(from: config)
            sections.append(shadowShowcaseSection(tokens: tokens))
            components.append(shadowCardComponent())
        }

        let bodySections = sections.joined(separator: "\n\n")

        var componentsSuffix = ""
        if !components.isEmpty {
            componentsSuffix = "\n\n// MARK: - Preview Components\n\n" + components.joined(separator: "\n\n")
        }

        let content = """
        // Generated by ThemeKit — do not edit

        import SwiftUI
        import ThemeKit

        /// A SwiftUI view that renders all theme tokens as a visual palette.
        public struct ThemePreview: View {

            public var body: some View {
                ScrollView {
                    VStack(alignment: .leading, spacing: 24) {
        \(bodySections.split(separator: "\n").map { "                \($0)" }.joined(separator: "\n"))
                    }
                    .padding()
                }
            }
        }

        #Preview {
            ThemePreview()
        }\(componentsSuffix)

        """
        return GeneratedFile(name: "Theme+Preview.swift", content: content)
    }

    // MARK: - Sections

    nonisolated func colorSwatchesSection(tokens: [ThemeToken]) -> String {
        let swatches = tokens.map { token in
            """
                        ColorSwatch(name: "\(token.name)", style: .\(token.style))
            """
        }.joined(separator: "\n")

        return """
        // MARK: - Colors
        VStack(alignment: .leading, spacing: 12) {
            Text("Colors")
                .font(.headline)
            LazyVGrid(columns: [GridItem(.adaptive(minimum: 96))], spacing: 12) {
        \(swatches)
            }
        }
        """
    }

    nonisolated func gradientStripsSection(tokens: [ThemeToken]) -> String {
        let strips = tokens.map { token in
            """
                        GradientStrip(name: "\(token.name)", style: .\(token.style))
            """
        }.joined(separator: "\n")

        return """
        // MARK: - Gradients
        VStack(alignment: .leading, spacing: 12) {
            Text("Gradients")
                .font(.headline)
            LazyVGrid(columns: [GridItem(.adaptive(minimum: 96))], spacing: 12) {
        \(strips)
            }
        }
        """
    }

    nonisolated func shadowShowcaseSection(tokens: [ThemeToken]) -> String {
        let cards = tokens.map { token in
            """
                    ShadowCard(name: "\(token.name)", style: .background.\(token.style))
            """
        }.joined(separator: "\n")

        return """
        // MARK: - Shadows
        VStack(alignment: .leading, spacing: 12) {
            Text("Shadows")
                .font(.headline)
            LazyVGrid(columns: [GridItem(.adaptive(minimum: 120))], spacing: 12) {
        \(cards)
            }
        }
        """
    }

    // MARK: - Components

    nonisolated func colorSwatchComponent() -> String {
        """
        private struct ColorSwatch<Style: ShapeStyle>: View {
            let name: String
            let style: Style

            var body: some View {
                VStack(alignment: .leading, spacing: 4) {
                    RoundedRectangle(cornerRadius: 8)
                        .fill(style)
                        .frame(height: 32)

                    Text(name)
                        .font(.caption)
                        .lineLimit(1)
                        .foregroundStyle(.secondary)
                }
            }
        }
        """
    }

    nonisolated func gradientStripComponent() -> String {
        """
        private struct GradientStrip<Style: ShapeStyle>: View {
            let name: String
            let style: Style

            var body: some View {
                VStack(alignment: .leading, spacing: 4) {
                    RoundedRectangle(cornerRadius: 8)
                        .fill(style)
                        .frame(height: 32)

                    Text(name)
                        .font(.caption)
                        .lineLimit(1)
                        .foregroundStyle(.secondary)
                }
            }
        }
        """
    }

    nonisolated func shadowCardComponent() -> String {
        """
        private struct ShadowCard<Style: ShapeStyle>: View {
            let name: String
            let style: Style

            var body: some View {
                VStack(alignment: .leading, spacing: 4) {
                    RoundedRectangle(cornerRadius: 12)
                        .fill(style)
                        .frame(height: 48)

                    Text(name)
                        .font(.caption)
                        .lineLimit(1)
                        .foregroundStyle(.secondary)
                }
            }
        }
        """
    }

}
