nonisolated public struct ThemePreviewGenerator: Sendable {

    nonisolated public init() {}

    nonisolated public func generate(from config: ThemeConfig) -> GeneratedFile {
        var sections: [String] = []

        // Generate color swatches if colors present
        if config.categories.contains(.colors) {
            let tokens = ThemeCategory.colors.tokens(from: config)
            sections.append(colorSwatchesSection(tokens: tokens))
        }

        // Generate gradient strips if gradients present
        if config.categories.contains(.gradients) {
            let tokens = ThemeCategory.gradients.tokens(from: config)
            sections.append(gradientStripsSection(tokens: tokens))
        }

        // Generate shadow showcase if shadows present
        if config.categories.contains(.shadows) {
            let tokens = ThemeCategory.shadows.tokens(from: config)
            sections.append(shadowShowcaseSection(tokens: tokens))
        }

        let bodySections = sections.joined(separator: "\n\n")

        let content = """
        // Generated by ThemeKit — do not edit

        import SwiftUI
        import ThemeKit

        /// A SwiftUI view that renders all theme tokens as a visual palette.
        public struct ThemePreview: View {
            @Environment(\\.theme) var theme
            @Environment(\\.self) var environment

            public init() {}

            public var body: some View {
                ScrollView {
                    VStack(alignment: .leading, spacing: 24) {
        \(bodySections.split(separator: "\n").map { "                \($0)" }.joined(separator: "\n"))
                    }
                    .padding()
                }
            }
        }

        #Preview {
            ThemePreview()
        }

        """
        return GeneratedFile(name: "Theme+Preview.swift", content: content)
    }

    nonisolated func colorSwatchesSection(tokens: [ThemeToken]) -> String {
        let swatches = tokens.map { token in
            """
                        ColorSwatch(name: "\(token.name)", color: theme.colors.\(token.name).resolved(in: environment))
            """
        }.joined(separator: "\n")

        return """
        // MARK: - Colors

        VStack(alignment: .leading, spacing: 12) {
            Text("Colors")
                .font(.headline)

            LazyVGrid(columns: [GridItem(.adaptive(minimum: 120))], spacing: 12) {
        \(swatches)
            }
        }
        """
    }

    nonisolated func gradientStripsSection(tokens: [ThemeToken]) -> String {
        let strips = tokens.map { token in
            """
                    GradientStrip(name: "\(token.name)", gradient: theme.gradients.\(token.name).resolved(in: environment))
            """
        }.joined(separator: "\n")

        return """
        // MARK: - Gradients

        VStack(alignment: .leading, spacing: 12) {
            Text("Gradients")
                .font(.headline)

            VStack(spacing: 12) {
        \(strips)
            }
        }
        """
    }

    nonisolated func shadowShowcaseSection(tokens: [ThemeToken]) -> String {
        let cards = tokens.map { token in
            """
                    ShadowCard(name: "\(token.name)", shadow: theme.shadows.\(token.name).resolved(in: environment))
            """
        }.joined(separator: "\n")

        return """
        // MARK: - Shadows

        VStack(alignment: .leading, spacing: 12) {
            Text("Shadows")
                .font(.headline)

            VStack(spacing: 12) {
        \(cards)
            }
        }
        """
    }
}

// MARK: - Preview Components

private struct ColorSwatch: View {
    let name: String
    let color: Color

    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            RoundedRectangle(cornerRadius: 8)
                .fill(color)
                .frame(height: 60)

            Text(name)
                .font(.caption)
                .foregroundStyle(.secondary)
        }
    }
}

private struct GradientStrip: View {
    let name: String
    let gradient: Gradient

    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            RoundedRectangle(cornerRadius: 8)
                .fill(LinearGradient(gradient: gradient, startPoint: .leading, endPoint: .trailing))
                .frame(height: 60)

            Text(name)
                .font(.caption)
                .foregroundStyle(.secondary)
        }
    }
}

private struct ShadowCard: View {
    let name: String
    let shadow: Shadow

    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            RoundedRectangle(cornerRadius: 12)
                .fill(.white)
                .frame(height: 80)
                .modifier(ShadowModifier(shadow: shadow))

            Text(name)
                .font(.caption)
                .foregroundStyle(.secondary)
        }
    }
}

private struct ShadowModifier: ViewModifier {
    let shadow: Shadow

    func body(content: Content) -> some View {
        switch shadow {
        case .none:
            content
        case .drop(let color, let radius, let x, let y):
            if let color {
                content.shadow(color: color, radius: radius, x: x, y: y)
            } else {
                content.shadow(radius: radius, x: x, y: y)
            }
        case .inner(let color, let radius, let x, let y):
            // Inner shadows are rendered via the ShadowStyle, but for preview we show as drop
            if let color {
                content.shadow(color: color, radius: radius, x: x, y: y)
            } else {
                content.shadow(radius: radius, x: x, y: y)
            }
        }
    }
}

