nonisolated public struct ThemeStructGenerator: Sendable {

    nonisolated public init() {}

    nonisolated public func generate(from config: ThemeConfig) -> GeneratedFile {
        let categories = config.categories

        let properties = categories.map { category in
            "    public let \(category.propertyName): \(category.structName)"
        }.joined(separator: "\n")

        let initParams = categories.map { category in
            "        \(category.propertyName): \(category.structName)"
        }.joined(separator: ",\n")

        let initAssignments = categories.map { category in
            "        self.\(category.propertyName) = \(category.propertyName)"
        }.joined(separator: "\n")

        let content = """
        // Generated by ThemeKit — do not edit

        import SwiftUI
        import ThemeKit

        nonisolated public struct Theme: Sendable, Codable, Equatable {
        \(properties)

            nonisolated public init(
        \(initParams)
            ) {
        \(initAssignments)
            }
        }

        """
        return GeneratedFile(name: "Theme.swift", content: content)
    }
}
